"""Tool implementations for TinyLLM."""

from tinyllm.tools.base import BaseTool, ToolConfig, ToolMetadata
from tinyllm.tools.calculator import CalculatorInput, CalculatorOutput, CalculatorTool
from tinyllm.tools.code_executor import (
    CodeExecutorConfig,
    CodeExecutorInput,
    CodeExecutorOutput,
    CodeExecutorTool,
)
from tinyllm.tools.filesystem import (
    CopyFileInput,
    CopyFileOutput,
    CopyFileTool,
    CreateDirectoryInput,
    CreateDirectoryOutput,
    CreateDirectoryTool,
    DeleteFileInput,
    DeleteFileOutput,
    DeleteFileTool,
    DirectoryInfo,
    FileInfo,
    FileInfoInput,
    FileInfoOutput,
    FileInfoTool,
    FileSystemConfig,
    FileSystemResult,
    FileType,
    ListDirectoryInput,
    ListDirectoryOutput,
    ListDirectoryTool,
    MoveFileInput,
    MoveFileOutput,
    MoveFileTool,
    ReadFileInput,
    ReadFileOutput,
    ReadFileTool,
    SearchFilesInput,
    SearchFilesOutput,
    SearchFilesTool,
    WriteFileInput,
    WriteFileOutput,
    WriteFileTool,
)
from tinyllm.tools.registry import ToolRegistry, register_default_tools
from tinyllm.tools.web_scraper import (
    ContentExtractor,
    ImageInfo,
    LinkInfo,
    OutputFormat,
    RobotsTxtChecker,
    ScrapeMode,
    ScrapedContent,
    ScraperCache,
    ScraperConfig,
    ScraperInput,
    ScraperResult,
    TableData,
    WebScraperTool,
)
from tinyllm.tools.web_search import (
    BraveSearchProvider,
    ContentFetcher,
    DuckDuckGoProvider,
    PageContent,
    RateLimiter,
    ResultDeduplicator,
    SearchCache,
    SearchProvider,
    SearchResult,
    SearXNGProvider,
    WebSearchConfig,
    WebSearchInput,
    WebSearchOutput,
    WebSearchTool,
)
from tinyllm.tools.analytics import (
    AnalyticsReport,
    AnalyticsToolWrapper,
    TimeBucket,
    TimeWindow,
    ToolStats,
    UsageAnalytics,
    UsageRecord,
    create_analytics,
    with_analytics,
)

__all__ = [
    # Base
    "BaseTool",
    "ToolConfig",
    "ToolMetadata",
    # Registry
    "ToolRegistry",
    "register_default_tools",
    # Calculator
    "CalculatorTool",
    "CalculatorInput",
    "CalculatorOutput",
    # Code Executor
    "CodeExecutorTool",
    "CodeExecutorInput",
    "CodeExecutorOutput",
    "CodeExecutorConfig",
    # Filesystem
    "FileSystemConfig",
    "FileSystemResult",
    "FileType",
    "FileInfo",
    "DirectoryInfo",
    "ReadFileTool",
    "ReadFileInput",
    "ReadFileOutput",
    "WriteFileTool",
    "WriteFileInput",
    "WriteFileOutput",
    "ListDirectoryTool",
    "ListDirectoryInput",
    "ListDirectoryOutput",
    "SearchFilesTool",
    "SearchFilesInput",
    "SearchFilesOutput",
    "CreateDirectoryTool",
    "CreateDirectoryInput",
    "CreateDirectoryOutput",
    "DeleteFileTool",
    "DeleteFileInput",
    "DeleteFileOutput",
    "MoveFileTool",
    "MoveFileInput",
    "MoveFileOutput",
    "CopyFileTool",
    "CopyFileInput",
    "CopyFileOutput",
    "FileInfoTool",
    "FileInfoInput",
    "FileInfoOutput",
    # Web Scraper
    "WebScraperTool",
    "ScraperInput",
    "ScraperResult",
    "ScraperConfig",
    "ScrapedContent",
    "ScrapeMode",
    "OutputFormat",
    "LinkInfo",
    "ImageInfo",
    "TableData",
    "ContentExtractor",
    "RobotsTxtChecker",
    "ScraperCache",
    # Web Search
    "WebSearchTool",
    "WebSearchInput",
    "WebSearchOutput",
    "WebSearchConfig",
    "SearchResult",
    "PageContent",
    "SearchProvider",
    "SearXNGProvider",
    "DuckDuckGoProvider",
    "BraveSearchProvider",
    "SearchCache",
    "RateLimiter",
    "ResultDeduplicator",
    "ContentFetcher",
    # Analytics
    "UsageAnalytics",
    "UsageRecord",
    "ToolStats",
    "TimeBucket",
    "TimeWindow",
    "AnalyticsReport",
    "AnalyticsToolWrapper",
    "with_analytics",
    "create_analytics",
]
